version: "3.6"

services:
  spooky_skeleton:
    build:
      context: ./
    volumes:
      - ./:/app/
    ports:
      - "5000:5000"
    environment:
      - REMOTE_SERVICE_URL=http://fake_remote_service:8083
    depends_on:
      - fake_remote_service

  fake_remote_service:
    image: jordimartin/mmock
    volumes:
      - ./docker/fake_remote_service:/config
    ports:
      - "8082:8082"

  spooky_skeleton_test:
    build:
      context: ./
      target: dev
    volumes:
      - ./:/app/
    command: "pytest tests"